### ISSUE TITLE
Provision of config file

### ISSUE THREAD

**Issue by gh-giant** [ovh/website-evidence-collector-batch#6]
Hi there,

thanks for the tool. I read through all the documentation but as I am new to programming and comand line tools I didn't manage to create the config file provided in https://github.com/ovh/website-evidence-collector-batch#configuration to JSON or YAML.

Could you please provide on as the tool won't work without.

Thanks in beforehand.

**Comment by blaryjp** [comment]
Hello,

Thank you. For sure I can help you:

Please create a YAML file (name it for example "config.yaml") with following content:

```yaml
output: './output'
firstPartyUri: 'https://www.example.com/'
urls:
  - 'https://www.example.com/url1'
  - 'https://www.example.com/url2'
sitemaps:
  - url: 'https://www.example.com/sitemap.xml'
```

- The "output" option is the directory where the reports will be saved.
- The "firstPartyUri" is the "base url" of the website
- Then, you can choose between setting "urls" and "sitemaps": you can for example use only a list of urls, or use only a list of sitemaps, or use both (like my example). If you put sitemaps, the tool will retreive the urls list from inside the sitemap.

Then, when you execute the tool, it will generates a report for each URL that you provided in that config file.

Tell me if I'm not clear, or if you want further informations ;).

Have a nice day,
